import styled from "styled-components";
import { keyframes } from "styled-components";

/* ----------------------------------------------
 * Generated by Animista on 2023-5-25 8:8:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-5x
 * ----------------------------------------
 */
const anim = keyframes`
    0% {
      background-color: #000000;
    }
    12% {
      background-color: #440077;
    }
    24% {
      background-color: #000000;
    }
    36% {
      background-color: #034010;
    }
    48% {
      background-color: #000000;
    }
    60% {
        background-color: #02256B;
      }
    72% {
        background-color: #000000;
      }
    84% {
        background-color: #371C3A;
      }
    100% {
        background-color: #000000;
      }
  }
 
  `;

const Background = styled.div`
  animation-name: ${anim};
  animation-duration: 20s;
  background-color: #19dcea;
  animation-iteration-count: infinite;
  width: 100vw;
  margin: 0 auto;
  height: auto;
  opacity: 0.8;
  text-align: center;
  @media only screen and (min-width: 600px) {
    display: fixed;
    height: 100%;
    width: 100%;
    grid-template-columns: 1 / span1;
  }
`;

interface Props {
  children: React.ReactNode;
}

export default function BackgroundGradientAnim({ children }: Props) {
  return <Background>{children}</Background>;
}
